In [1]:
import requests
import pandas as pd

# Set your backend URL
BASE_URL = "http://localhost:8000/orats"

# Sample ticker for testing
TICKER = "IBIT"

# Helper function to pretty-print DataFrame or raw JSON
def preview(response):
    try:
        data = response.json()
        if isinstance(data, dict) and "data" in data:
            return pd.DataFrame(data["data"])
        return data
    except Exception as e:
        print("Error:", e)
        print(response.text)
        return None

In [2]:

# 1. Get Strikes
r_strikes = requests.get(f"{BASE_URL}/strikes", params={"ticker": TICKER})
print("✅ /strikes")
display(preview(r_strikes))

ConnectionError: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /orats/strikes?ticker=IBIT (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000027839B23A50>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))

In [ ]:

# 5. Get forecasts
r_forecasts = requests.get(f"{BASE_URL}/forecast", params={"ticker": TICKER})
print("✅ /forecast")
display(preview(r_forecasts))

✅ /forecast

,ticker,tradeDate,expirDate,stockPrice,riskFreeRate,vol100,vol95,vol90,vol85,vol80,...,vol20,vol15,vol10,vol5,vol0,quoteDate,updatedAt,snapShotEstTime,snapShotDate,expiryTod
0,IBIT,2025-05-29,2025-05-30,60.67,0.0435,0.540365,0.490950,0.468317,0.454094,0.441210,...,0.462636,0.470092,0.478419,0.487618,0.497690,2025-05-29T16:51:47Z,2025-05-29T16:51:53Z,1252,2025-05-29T16:52:00Z,pm
1,IBIT,2025-05-29,2025-06-06,60.67,0.0435,0.540365,0.490950,0.468317,0.454094,0.441210,...,0.462636,0.470092,0.478419,0.487618,0.497690,2025-05-29T16:51:47Z,2025-05-29T16:51:53Z,1252,2025-05-29T16:52:00Z,pm
2,IBIT,2025-05-29,2025-06-13,60.67,0.0435,0.540365,0.490950,0.468317,0.454094,0.441210,...,0.462636,0.470092,0.478419,0.487618,0.497690,2025-05-29T16:51:47Z,2025-05-29T16:51:53Z,1252,2025-05-29T16:52:00Z,pm
3,IBIT,2025-05-29,2025-06-20,60.67,0.0435,0.540365,0.490950,0.468317,0.454094,0.441210,...,0.462636,0.470092,0.478419,0.487618,0.497690,2025-05-29T16:51:47Z,2025-05-29T16:51:53Z,1252,2025-05-29T16:52:00Z,pm
4,IBIT,2025-05-29,2025-06-27,60.67,0.0435,0.539784,0.490324,0.467652,0.453394,0.440482,...,0.461988,0.469485,0.477860,0.487112,0.497242,2025-05-29T16:51:47Z,2025-05-29T16:51:53Z,1252,2025-05-29T16:52:00Z,pm
5,IBIT,2025-05-29,2025-06-30,60.67,0.0435,0.539011,0.489492,0.466769,0.452466,0.439516,...,0.461128,0.468680,0.477117,0.486438,0.496645,2025-05-29T16:51:47Z,2025-05-29T16:51:53Z,1252,2025-05-29T16:52:00Z,pm
6,IBIT,2025-05-29,2025-07-03,60.67,0.0435,0.538337,0.488766,0.465998,0.451657,0.438674,...,0.460376,0.467976,0.476467,0.485849,0.496122,2025-05-29T16:51:47Z,2025-05-29T16:51:53Z,1252,2025-05-29T16:52:00Z,pm
7,IBIT,2025-05-29,2025-07-11,60.67,0.0435,0.536884,0.487205,0.464340,0.449916,0.436864,...,0.458760,0.466462,0.475068,0.484578,0.494992,2025-05-29T16:51:47Z,2025-05-29T16:51:53Z,1252,2025-05-29T16:52:00Z,pm
8,IBIT,2025-05-29,2025-07-18,60.67,0.0435,0.535901,0.486149,0.463220,0.448741,0.435643,...,0.457668,0.465438,0.474120,0.483716,0.494224,2025-05-29T16:51:47Z,2025-05-29T16:51:53Z,1252,2025-05-29T16:52:00Z,pm
9,IBIT,2025-05-29,2025-07-31,60.67,0.0435,0.534520,0.484667,0.461650,0.447094,0.433931,...,0.456135,0.463999,0.472788,0.482502,0.493141,2025-05-29T16:51:47Z,2025-05-29T16:51:53Z,1252,2025-05-29T16:52:00Z,pm
10,IBIT,2025-05-29,2025-08-15,60.67,0.0435,0.533369,0.483432,0.460342,0.445723,0.432507,...,0.454858,0.462799,0.471676,0.481487,0.492234,2025-05-29T16:51:47Z,2025-05-29T16:51:53Z,1252,2025-05-29T16:52:00Z,pm
11,IBIT,2025-05-29,2025-08-29,60.67,0.0436,0.532554,0.482560,0.459418,0.444755,0.431502,...,0.453955,0.461951,0.470889,0.480769,0.491591,2025-05-29T16:51:47Z,2025-05-29T16:51:53Z,1252,2025-05-29T16:52:00Z,pm
12,IBIT,2025-05-29,2025-09-19,60.67,0.0436,0.531624,0.481564,0.458365,0.443652,0.430356,...,0.452926,0.460983,0.469990,0.479947,0.490854,2025-05-29T16:51:47Z,2025-05-29T16:51:53Z,1252,2025-05-29T16:52:00Z,pm
13,IBIT,2025-05-29,2025-09-30,60.67,0.0436,0.531233,0.481145,0.457922,0.443188,0.429875,...,0.452493,0.460575,0.469611,0.479601,0.490543,2025-05-29T16:51:47Z,2025-05-29T16:51:53Z,1252,2025-05-29T16:52:00Z,pm
14,IBIT,2025-05-29,2025-10-31,60.67,0.0436,0.530361,0.480213,0.456936,0.442156,0.428804,...,0.451529,0.459668,0.468768,0.478829,0.489850,2025-05-29T16:51:47Z,2025-05-29T16:51:53Z,1252,2025-05-29T16:52:00Z,pm
15,IBIT,2025-05-29,2025-11-21,60.67,0.0436,0.529905,0.479725,0.456420,0.441616,0.428245,...,0.451025,0.459193,0.468326,0.478424,0.489486,2025-05-29T16:51:47Z,2025-05-29T16:51:53Z,1252,2025-05-29T16:52:00Z,pm
16,IBIT,2025-05-29,2025-11-28,60.67,0.0416,0.529771,0.479581,0.456268,0.441457,0.428080,...,0.450876,0.459053,0.468196,0.478305,0.489379,2025-05-29T16:51:47Z,2025-05-29T16:51:53Z,1252,2025-05-29T16:52:00Z,pm
17,IBIT,2025-05-29,2025-12-19,60.67,0.0416,0.529409,0.479195,0.455860,0.441030,0.427637,...,0.450477,0.458677,0.467846,0.477984,0.489090,2025-05-29T16:51:47Z,2025-05-29T16:51:53Z,1252,2025-05-29T16:52:00Z,pm
18,IBIT,2025-05-29,2025-12-31,60.67,0.0416,0.529227,0.479000,0.455654,0.440814,0.427413,...,0.450275,0.458487,0.467669,0.477822,0.488944,2025-05-29T16:51:47Z,2025-05-29T16:51:53Z,1252,2025-05-29T16:52:00Z,pm
19,IBIT,2025-05-29,2026-01-16,60.67,0.0416,0.529005,0.478763,0.455404,0.440553,0.427142,...,0.450031,0.458257,0.467455,0.477625,0.488767,2025-05-29T16:51:47Z,2025-05-29T16:51:53Z,1252,2025-05-29T16:52:00Z,pm
20,IBIT,2025-05-29,2026-03-20,60.67,0.0416,0.528315,0.478026,0.454625,0.439738,0.426297,...,0.449268,0.457538,0.466786,0.477011,0.488214,2025-05-29T16:51:47Z,2025-05-29T16:51:53Z,1252,2025-05-29T16:52:00Z,pm
21,IBIT,2025-05-29,2026-06-18,60.67,0.0396,0.527638,0.477304,0.453862,0.438941,0.425471,...,0.448522,0.456835,0.466130,0.476409,0.487671,2025-05-29T16:51:47Z,2025-05-29T16:51:53Z,1252,2025-05-29T16:52:00Z,pm
22,IBIT,2025-05-29,2027-01-15,60.67,0.0396,0.526703,0.476305,0.452809,0.437840,0.424330,...,0.447491,0.455862,0.465223,0.475576,0.486919,2025-05-29T16:51:47Z,2025-05-29T16:51:53Z,1252,2025-05-29T16:52:00Z,pm
23,IBIT,2025-05-29,2027-12-17,60.67,0.0395,0.525934,0.475485,0.451943,0.436936,0.423392,...,0.446643,0.455061,0.464476,0.474889,0.486298,2025-05-29T16:51:47Z,2025-05-29T16:51:53Z,1252,2025-05-29T16:52:00Z,pm

In [ ]:

# 8. Get Forward Curve
r_implied = requests.get(f"{BASE_URL}/implied", params={"ticker": TICKER})
print("✅ /implied")
display(preview(r_implied))

✅ /implied

,ticker,tradeDate,expirDate,stockPrice,riskFreeRate,yieldRate,residualYieldRate,residualRateSlp,residualR2,confidence,...,fit,spotPrice,calVol,unadjVol,earnEffect,quoteDate,updatedAt,snapShotEstTime,snapShotDate,expiryTod
0,IBIT,2025-05-29,2025-05-30,60.7,0.0435,0,-0.117742,0.000000,2.952930,0.579834,...,0.000021,60.7,0.391525,0.391525,0,2025-05-29T16:50:58Z,2025-05-29T16:51:04Z,1251,2025-05-29T16:51:00Z,pm
1,IBIT,2025-05-29,2025-06-06,60.7,0.0435,0,-0.016519,0.000000,0.051498,0.974982,...,0.000011,60.7,0.409262,0.409262,0,2025-05-29T16:50:58Z,2025-05-29T16:51:04Z,1251,2025-05-29T16:51:00Z,pm
2,IBIT,2025-05-29,2025-06-13,60.7,0.0435,0,-0.011034,0.000000,0.031037,0.971735,...,0.000021,60.7,0.420448,0.420448,0,2025-05-29T16:50:58Z,2025-05-29T16:51:04Z,1251,2025-05-29T16:51:00Z,pm
3,IBIT,2025-05-29,2025-06-20,60.7,0.0435,0,-0.012984,0.000000,0.021193,1.000000,...,0.000023,60.7,0.429349,0.429349,0,2025-05-29T16:50:58Z,2025-05-29T16:51:04Z,1251,2025-05-29T16:51:00Z,pm
4,IBIT,2025-05-29,2025-06-27,60.7,0.0435,0,-0.011995,0.000000,0.007980,1.000000,...,0.000027,60.7,0.436971,0.436971,0,2025-05-29T16:50:58Z,2025-05-29T16:51:04Z,1251,2025-05-29T16:51:00Z,pm
5,IBIT,2025-05-29,2025-06-30,60.7,0.0435,0,-0.010113,0.000000,0.014668,0.998371,...,0.000014,60.7,0.439961,0.439961,0,2025-05-29T16:50:58Z,2025-05-29T16:51:04Z,1251,2025-05-29T16:51:00Z,pm
6,IBIT,2025-05-29,2025-07-03,60.7,0.0435,0,-0.012344,0.000000,0.007786,1.000000,...,0.000039,60.7,0.442818,0.442818,0,2025-05-29T16:50:58Z,2025-05-29T16:51:04Z,1251,2025-05-29T16:51:00Z,pm
7,IBIT,2025-05-29,2025-07-11,60.7,0.0435,0,-0.012728,0.000000,0.005393,0.564421,...,0.000010,60.7,0.449901,0.449901,0,2025-05-29T16:50:58Z,2025-05-29T16:51:04Z,1251,2025-05-29T16:51:00Z,pm
8,IBIT,2025-05-29,2025-07-18,60.7,0.0435,0,-0.012281,0.001247,0.004352,0.959392,...,0.000015,60.7,0.458734,0.458734,0,2025-05-29T16:50:58Z,2025-05-29T16:51:04Z,1251,2025-05-29T16:51:00Z,pm
9,IBIT,2025-05-29,2025-07-31,60.7,0.0435,0,-0.011480,0.004583,0.003212,0.927442,...,0.000016,60.7,0.472018,0.472018,0,2025-05-29T16:50:58Z,2025-05-29T16:51:04Z,1251,2025-05-29T16:51:00Z,pm
10,IBIT,2025-05-29,2025-08-15,60.7,0.0435,0,-0.011804,0.003523,0.002167,1.000000,...,0.000021,60.7,0.483060,0.483060,0,2025-05-29T16:50:58Z,2025-05-29T16:51:04Z,1251,2025-05-29T16:51:00Z,pm
11,IBIT,2025-05-29,2025-08-29,60.7,0.0436,0,-0.011579,0.000442,0.000876,0.863175,...,0.000018,60.7,0.490851,0.490851,0,2025-05-29T16:50:58Z,2025-05-29T16:51:04Z,1251,2025-05-29T16:51:00Z,pm
12,IBIT,2025-05-29,2025-09-19,60.7,0.0436,0,-0.011170,0.005077,0.001699,1.000000,...,0.000020,60.7,0.499722,0.499722,0,2025-05-29T16:50:58Z,2025-05-29T16:51:04Z,1251,2025-05-29T16:51:00Z,pm
13,IBIT,2025-05-29,2025-09-30,60.7,0.0436,0,-0.010132,0.000321,0.001094,0.808823,...,0.000043,60.7,0.503449,0.503449,0,2025-05-29T16:50:58Z,2025-05-29T16:51:04Z,1251,2025-05-29T16:51:00Z,pm
14,IBIT,2025-05-29,2025-10-31,60.7,0.0436,0,-0.010453,0.000024,0.000979,0.765930,...,0.000034,60.7,0.511740,0.511740,0,2025-05-29T16:50:58Z,2025-05-29T16:51:04Z,1251,2025-05-29T16:51:00Z,pm
15,IBIT,2025-05-29,2025-11-21,60.7,0.0436,0,-0.010103,-0.004386,0.000584,0.896606,...,0.000029,60.7,0.516070,0.516070,0,2025-05-29T16:50:58Z,2025-05-29T16:51:04Z,1251,2025-05-29T16:51:00Z,pm
16,IBIT,2025-05-29,2025-11-28,60.7,0.0416,0,-0.012011,-0.001967,0.000342,0.785465,...,0.000027,60.7,0.517347,0.517347,0,2025-05-29T16:50:58Z,2025-05-29T16:51:04Z,1251,2025-05-29T16:51:00Z,pm
17,IBIT,2025-05-29,2025-12-19,60.7,0.0416,0,-0.011282,-0.002594,0.000316,0.895711,...,0.000028,60.7,0.520775,0.520775,0,2025-05-29T16:50:58Z,2025-05-29T16:51:04Z,1251,2025-05-29T16:51:00Z,pm
18,IBIT,2025-05-29,2025-12-31,60.7,0.0416,0,-0.011741,-0.002353,0.000316,0.705867,...,0.000031,60.7,0.522506,0.522506,0,2025-05-29T16:50:58Z,2025-05-29T16:51:04Z,1251,2025-05-29T16:51:00Z,pm
19,IBIT,2025-05-29,2026-01-16,60.7,0.0416,0,-0.011262,-0.002506,0.000464,0.929369,...,0.000032,60.7,0.524603,0.524603,0,2025-05-29T16:50:58Z,2025-05-29T16:51:04Z,1251,2025-05-29T16:51:00Z,pm
20,IBIT,2025-05-29,2026-03-20,60.7,0.0416,0,-0.011006,-0.002899,0.000098,0.820734,...,0.000019,60.7,0.531134,0.531134,0,2025-05-29T16:50:58Z,2025-05-29T16:51:04Z,1251,2025-05-29T16:51:00Z,pm
21,IBIT,2025-05-29,2026-06-18,60.7,0.0396,0,-0.012265,-0.002334,0.000118,0.759946,...,0.000018,60.7,0.537521,0.537521,0,2025-05-29T16:50:58Z,2025-05-29T16:51:04Z,1251,2025-05-29T16:51:00Z,pm
22,IBIT,2025-05-29,2027-01-15,60.7,0.0396,0,-0.009619,-0.003044,0.000063,0.720638,...,0.000025,60.7,0.546335,0.546335,0,2025-05-29T16:50:58Z,2025-05-29T16:51:04Z,1251,2025-05-29T16:51:00Z,pm
23,IBIT,2025-05-29,2027-12-17,60.7,0.0395,0,-0.007079,-0.000755,0.000008,0.527642,...,0.000012,60.7,0.553574,0.553574,0,2025-05-29T16:50:58Z,2025-05-29T16:51:04Z,1251,2025-05-29T16:51:00Z,pm